// src/components/UISpec/ScreenEditor/ViewPort/EditorCanvas.vue
<template>
  <svg
    ref="svg"
    :width="zoomedWidth"
    :height="zoomedHeight"
    :viewBox="viewbox"
    class="EditorCanvas"
    @click="onClickSVG"
  >
    <image
      v-bind="{ 'xlink:href': imageSrc }"
      :width="editScreen.width"
      :height="editScreen.height"
      class="EditorCanvas_Image"
    />
    <Highlight
      v-for="(coordinate, index) in coordinates"
      :key="index"
      :order="index"
      :coordinate="coordinate"
      :selected="index === coordinate.selectedItem"
      :width="editScreen.width"
      :height="editScreen.height"
      :getCoordinateByXY="getCoordinateByXY"
      @selectHighlight="onSelectHighlight"
      @setCoordinates="onSetCoordinates"
    />
  </svg>
</template>

<script>
import Highlight from './EditorCanvas/Highlight.vue'
export default {
  name: 'EditorCanvas',
  components: {
    Highlight,
  },
  props: {
    editScreen: {
      type: Object,
      required: true,
    },
    coordinates: {
      type: Array,
      required: true,
    },
    zoomedWidth: {
      type: Number,
      required: true,
    },
    zoomedHeight: {
      type: Number,
      required: true,
    },
    viewbox: {
      type: String,
      required: true,
    },
  },
  computed: {
    imageSrc() {
      return this.editScreen.srcBase64 ? this.editScreen.srcBase64 : this.editScreen.src
    },
  },
  created() {
    this._handleKeyDown = this._handleKeyDown.bind(this)
  },
  mounted() {
    document.removeEventListener('keydown', this._handleKeyDown)
    document.addEventListener('keydown', this._handleKeyDown)
  },
  unmounted() {
    document.removeEventListener('keydown', this._handleKeyDown)
  },
  methods: {
    onSelectHighlight(order) {
      this.$emit('selectHighlight', order)
    },
    onSetCoordinates({ order, coordinateArray }) {
      this.$emit('setCoordinates', { order, coordinateArray })
    },
    removeHighlight() {
      this.$emit('removeHighlight')
    },
    _handleKeyDown(e) {
      if (e.keyCode === 8) {
        this.removeHighlight()
      }
    },
    onClickSVG(e) {
      e.preventDefault
      e.stopPropagation()
      if (!e.target.classList.contains('EditorCanvas_Image')) {
        return
      }
      const { x, y } = this.getCoordinateByXY(e)
      this.addHighlight({ x, y })
    },
    getCoordinateByXY({ x, y }) {
      let svg = this.$refs.svg
      let p = svg.createSVGPoint()
      p.x = x | 0
      p.y = y | 0
      const transformed = p.matrixTransform(svg.getScreenCTM().inverse())
      return {
        x: Math.round(transformed.x),
        y: Math.round(transformed.y),
      }
    },
    addHighlight({ x, y }) {
      this.$emit('addHighlight', { x, y })
    },
  },
}
</script>

<style lang="scss" scoped>
.EditorCanvas {
  transition: all 0.3s;
  cursor: crosshair;
  &_Image {
  }
}
</style>

// lib/editor/src/js/component/EditorCanvas.jsx
const React     = require( 'react' );
const store     = require( '../store.js' );
const Highlight = require( './Highlight.jsx' );

class EditorCanvas extends React.Component {

	addHighlight ( e ) {

		e.nativeEvent.preventDefault();
		e.nativeEvent.stopPropagation();

		if ( !e.target.classList.contains( 'EDT-EditorCanvas__image' ) ) { return; }

		let svg = this.refs.svg;
		let p   = svg.createSVGPoint();
		p.x = e.nativeEvent.x | 0;
		p.y = e.nativeEvent.y | 0;
		let svgCoord = p.matrixTransform( svg.getScreenCTM().inverse() );

		store.dispatch( {
			type: 'HIGHLIGHT_ADD',
			coord: [ svgCoord.x, svgCoord.y, 100, 100 ]
		} );

	}

	getCoordByXY( { x, y } ) {

		let svg = this.refs.svg;
		let p   = svg.createSVGPoint();
		p.x = x | 0;
		p.y = y | 0;

		return p.matrixTransform( svg.getScreenCTM().inverse() );

	}

	render () {

		let { src, zoom, coords, selectedItem } = this.props,
				w = this.props.width,
				h = this.props.height,
				viewbox = `0 0 ${ w } ${ h }`;

		let getCoordByXY = this.getCoordByXY.bind( this );

		return (
			<svg
				ref="svg"
				className="EDT-EditorCanvas"
				width={ w * zoom } height={ h * zoom } viewBox={ viewbox }
				onClick={ this.addHighlight.bind( this ) }
			>
				<image xlinkHref={ src } width={ w } height={ h } className="EDT-EditorCanvas__image" />

				{ coords.map( function ( coord, i ) {

					return (
						<Highlight
							key={ i } order={ i }
							coord={ coord }
							selected={ i === selectedItem }
							getCoordByXY={ getCoordByXY }
						/>
					);

				} ) }

			</svg>
		);

	}

}

module.exports = EditorCanvas;
